// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: core.proto

package socket

import (
	"context"

	"sokuim/sokuim-server/app/core/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SocketConnectReq     = pb.SocketConnectReq
	SocketConnectResp    = pb.SocketConnectResp
	SocketDisconnectReq  = pb.SocketDisconnectReq
	SocketDisconnectResp = pb.SocketDisconnectResp
	SocketHeartbeatReq   = pb.SocketHeartbeatReq
	SocketHeartbeatResp  = pb.SocketHeartbeatResp
	SocketMsgProto       = pb.SocketMsgProto
	SocketOnlineReq      = pb.SocketOnlineReq
	SocketOnlineResp     = pb.SocketOnlineResp
	SocketReceiveReq     = pb.SocketReceiveReq
	SocketReceiveResp    = pb.SocketReceiveResp

	Socket interface {
		// Connect valid socket connect
		Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error)
		Disconnect(ctx context.Context, in *SocketDisconnectReq, opts ...grpc.CallOption) (*SocketDisconnectResp, error)
		RenewOnline(ctx context.Context, in *SocketOnlineReq, opts ...grpc.CallOption) (*SocketOnlineResp, error)
		Heartbeat(ctx context.Context, in *SocketHeartbeatReq, opts ...grpc.CallOption) (*SocketHeartbeatResp, error)
		Receive(ctx context.Context, in *SocketReceiveReq, opts ...grpc.CallOption) (*SocketReceiveResp, error)
	}

	defaultSocket struct {
		cli zrpc.Client
	}
)

func NewSocket(cli zrpc.Client) Socket {
	return &defaultSocket{
		cli: cli,
	}
}

// Connect valid socket connect
func (m *defaultSocket) Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.Connect(ctx, in, opts...)
}

func (m *defaultSocket) Disconnect(ctx context.Context, in *SocketDisconnectReq, opts ...grpc.CallOption) (*SocketDisconnectResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.Disconnect(ctx, in, opts...)
}

func (m *defaultSocket) RenewOnline(ctx context.Context, in *SocketOnlineReq, opts ...grpc.CallOption) (*SocketOnlineResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.RenewOnline(ctx, in, opts...)
}

func (m *defaultSocket) Heartbeat(ctx context.Context, in *SocketHeartbeatReq, opts ...grpc.CallOption) (*SocketHeartbeatResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.Heartbeat(ctx, in, opts...)
}

func (m *defaultSocket) Receive(ctx context.Context, in *SocketReceiveReq, opts ...grpc.CallOption) (*SocketReceiveResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.Receive(ctx, in, opts...)
}
