// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: core.proto

package socket

import (
	"context"

	"sokuim/sokuim-server/app/core/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SocketConnectReq  = pb.SocketConnectReq
	SocketConnectResp = pb.SocketConnectResp

	Socket interface {
		// Connect valid socket connect
		Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error)
	}

	defaultSocket struct {
		cli zrpc.Client
	}
)

func NewSocket(cli zrpc.Client) Socket {
	return &defaultSocket{
		cli: cli,
	}
}

// Connect valid socket connect
func (m *defaultSocket) Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error) {
	client := pb.NewSocketClient(m.cli.Conn())
	return client.Connect(ctx, in, opts...)
}
