// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: core.proto

package server

import (
	"context"

	"sokuim/sokuim-server/app/core/internal/logic/socket"
	"sokuim/sokuim-server/app/core/internal/svc"
	"sokuim/sokuim-server/app/core/pb"
)

type SocketServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSocketServer
}

func NewSocketServer(svcCtx *svc.ServiceContext) *SocketServer {
	return &SocketServer{
		svcCtx: svcCtx,
	}
}

// Connect valid socket connect
func (s *SocketServer) Connect(ctx context.Context, in *pb.SocketConnectReq) (*pb.SocketConnectResp, error) {
	l := socketlogic.NewConnectLogic(ctx, s.svcCtx)
	return l.Connect(in)
}

func (s *SocketServer) Disconnect(ctx context.Context, in *pb.SocketDisconnectReq) (*pb.SocketDisconnectResp, error) {
	l := socketlogic.NewDisconnectLogic(ctx, s.svcCtx)
	return l.Disconnect(in)
}

func (s *SocketServer) RenewOnline(ctx context.Context, in *pb.SocketOnlineReq) (*pb.SocketOnlineResp, error) {
	l := socketlogic.NewRenewOnlineLogic(ctx, s.svcCtx)
	return l.RenewOnline(in)
}

func (s *SocketServer) Heartbeat(ctx context.Context, in *pb.SocketHeartbeatReq) (*pb.SocketHeartbeatResp, error) {
	l := socketlogic.NewHeartbeatLogic(ctx, s.svcCtx)
	return l.Heartbeat(in)
}

func (s *SocketServer) Receive(ctx context.Context, in *pb.SocketReceiveReq) (*pb.SocketReceiveResp, error) {
	l := socketlogic.NewReceiveLogic(ctx, s.svcCtx)
	return l.Receive(in)
}
