// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: comet.proto

package server

import (
	"context"

	"sokuim/sokuim-server/app/comet/internal/logic/comet"
	"sokuim/sokuim-server/app/comet/internal/svc"
	"sokuim/sokuim-server/app/comet/pb"
)

type CometServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCometServer
}

func NewCometServer(svcCtx *svc.ServiceContext) *CometServer {
	return &CometServer{
		svcCtx: svcCtx,
	}
}

func (s *CometServer) PushMsgCommon(ctx context.Context, in *pb.CometPushCommonReq) (*pb.CometPushCommonResp, error) {
	l := cometlogic.NewPushMsgCommonLogic(ctx, s.svcCtx)
	return l.PushMsgCommon(in)
}
