// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: comet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CometPushCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   int32  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CometPushCommonReq) Reset() {
	*x = CometPushCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometPushCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometPushCommonReq) ProtoMessage() {}

func (x *CometPushCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometPushCommonReq.ProtoReflect.Descriptor instead.
func (*CometPushCommonReq) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{0}
}

func (x *CometPushCommonReq) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *CometPushCommonReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type CometPushCommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CometPushCommonResp) Reset() {
	*x = CometPushCommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CometPushCommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CometPushCommonResp) ProtoMessage() {}

func (x *CometPushCommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CometPushCommonResp.ProtoReflect.Descriptor instead.
func (*CometPushCommonResp) Descriptor() ([]byte, []int) {
	return file_comet_proto_rawDescGZIP(), []int{1}
}

var File_comet_proto protoreflect.FileDescriptor

var file_comet_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x43,
	0x6f, 0x6d, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x32, 0x49, 0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comet_proto_rawDescOnce sync.Once
	file_comet_proto_rawDescData = file_comet_proto_rawDesc
)

func file_comet_proto_rawDescGZIP() []byte {
	file_comet_proto_rawDescOnce.Do(func() {
		file_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_comet_proto_rawDescData)
	})
	return file_comet_proto_rawDescData
}

var file_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comet_proto_goTypes = []interface{}{
	(*CometPushCommonReq)(nil),  // 0: pb.CometPushCommonReq
	(*CometPushCommonResp)(nil), // 1: pb.CometPushCommonResp
}
var file_comet_proto_depIdxs = []int32{
	0, // 0: pb.Comet.PushMsgCommon:input_type -> pb.CometPushCommonReq
	1, // 1: pb.Comet.PushMsgCommon:output_type -> pb.CometPushCommonResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comet_proto_init() }
func file_comet_proto_init() {
	if File_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometPushCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CometPushCommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comet_proto_goTypes,
		DependencyIndexes: file_comet_proto_depIdxs,
		MessageInfos:      file_comet_proto_msgTypes,
	}.Build()
	File_comet_proto = out.File
	file_comet_proto_rawDesc = nil
	file_comet_proto_goTypes = nil
	file_comet_proto_depIdxs = nil
}
