version: '3.8'

services:
  comet:
    image: ghcr.io/sokuim/sokuim-server/comet:latest
    container_name: sokuim-comet
    restart: always
    ports:
      - "${COMET_PORT}:8082"
    volumes:
      - /etc/localtime:/etc/localtime:ro # timezone
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/common/healthz || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s