services:
  gateway:
    image: ghcr.io/sokuim/sokuim-server/gateway:latest
    container_name: sokuim-gateway
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro # timezone
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/common/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s