version: '3.8'

services:
  gateway:
    image: ghcr.io/sokuim/sokuim-server/gateway:latest
    container_name: sokuim-gateway
    restart: always
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - /etc/localtime:/etc/localtime:ro # timezone
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${GATEWAY_PORT}/common/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s