// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	common "sokuim/sokuim-server/app/gateway/internal/handler/common"
	"sokuim/sokuim-server/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Healthz check
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: common.HealthzHandler(serverCtx),
			},
		},
		rest.WithPrefix("/common"),
	)
}
