syntax = "proto3";

package pb;
option go_package = "./pb";

message SocketConnectReq {
  string Server = 1;
  string Cookie = 2;
  bytes Token = 3;
}

message SocketConnectResp {
  string MID = 1; // member ID
  string Key = 2;
  string Server = 3;
}

message SocketOnlineReq {
  string server = 1;
  map<string, int32> roomCount = 2;
}

message SocketOnlineResp {
  map<string, int32> allRoomCount = 1;
}

service Socket {
  // Connect valid socket connect
  rpc Connect (SocketConnectReq) returns (SocketConnectResp);
  rpc RenewOnline(SocketOnlineReq) returns (SocketOnlineResp);
}