services:
  job:
    image: ghcr.io/sokuim/sokuim-server/job:latest
    container_name: sokuim-job
    restart: unless-stopped
    ports:
      - "${JOB_PORT}:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro # async timezone
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/common/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s