// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: comet.proto

package comet

import (
	"context"

	"sokuim/sokuim-server/app/comet/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CometBroadcastRoomReq  = pb.CometBroadcastRoomReq
	CometBroadcastRoomResp = pb.CometBroadcastRoomResp
	CometMsgProto          = pb.CometMsgProto
	CometPushCommonReq     = pb.CometPushCommonReq
	CometPushCommonResp    = pb.CometPushCommonResp

	Comet interface {
		PushMsgCommon(ctx context.Context, in *CometPushCommonReq, opts ...grpc.CallOption) (*CometPushCommonResp, error)
	}

	defaultComet struct {
		cli zrpc.Client
	}
)

func NewComet(cli zrpc.Client) Comet {
	return &defaultComet{
		cli: cli,
	}
}

func (m *defaultComet) PushMsgCommon(ctx context.Context, in *CometPushCommonReq, opts ...grpc.CallOption) (*CometPushCommonResp, error) {
	client := pb.NewCometClient(m.cli.Conn())
	return client.PushMsgCommon(ctx, in, opts...)
}
