name: sokuim server auto-release

on:
  push:
    branches:
      - main
      - master
    paths: # paths中的代码发生变化时，触发 action
      - "main.go"
      - "go.mod"
      - ".github/workflows/release.yml"
      - "app/comet/comet.go"
      - "app/core/core.go"
      - "app/gateway/gateway.go"

jobs:
  check-changes:
    runs-on: ubuntu-latest # runner 运行环境
    outputs:
      comet: ${{ steps.filter.outputs.comet }} # comet服务需要监控的文件
      core: ${{ steps.filter.outputs.core }} # core服务需要监控的文件
      gateway: ${{ steps.filter.outputs.gateway }} # gateway服务需要监控的文件
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #拉取git的所有历史记录，包含分支、comet、tag, 1时只拉取最近一次

      - name: Get change files
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            comet:
              - go.mod
              - app/comet/comet.go
              - .github/workflows/release.yml
            core:
              - go.mod
              - app/core/core.go
              - .github/workflows/release.yml
            gateway:
              - go.mod
              - app/gateway/gateway.go
              - .github/workflows/release.yml
      - name: debug output
        run: |
          echo "release comet: ${{ steps.filter.outputs.comet }}"
          echo "release core: ${{ steps.filter.outputs.core }}"
          echo "release gateway: ${{ steps.filter.outputs.gateway }}"
          echo "current branch: ${{ github.ref_name }}"