// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SocketClient is the client API for Socket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocketClient interface {
	// Connect valid socket connect
	Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error)
	Disconnect(ctx context.Context, in *SocketDisconnectReq, opts ...grpc.CallOption) (*SocketDisconnectResp, error)
	RenewOnline(ctx context.Context, in *SocketOnlineReq, opts ...grpc.CallOption) (*SocketOnlineResp, error)
	Heartbeat(ctx context.Context, in *SocketHeartbeatReq, opts ...grpc.CallOption) (*SocketHeartbeatResp, error)
	Receive(ctx context.Context, in *SocketReceiveReq, opts ...grpc.CallOption) (*SocketReceiveResp, error)
}

type socketClient struct {
	cc grpc.ClientConnInterface
}

func NewSocketClient(cc grpc.ClientConnInterface) SocketClient {
	return &socketClient{cc}
}

func (c *socketClient) Connect(ctx context.Context, in *SocketConnectReq, opts ...grpc.CallOption) (*SocketConnectResp, error) {
	out := new(SocketConnectResp)
	err := c.cc.Invoke(ctx, "/pb.Socket/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) Disconnect(ctx context.Context, in *SocketDisconnectReq, opts ...grpc.CallOption) (*SocketDisconnectResp, error) {
	out := new(SocketDisconnectResp)
	err := c.cc.Invoke(ctx, "/pb.Socket/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) RenewOnline(ctx context.Context, in *SocketOnlineReq, opts ...grpc.CallOption) (*SocketOnlineResp, error) {
	out := new(SocketOnlineResp)
	err := c.cc.Invoke(ctx, "/pb.Socket/RenewOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) Heartbeat(ctx context.Context, in *SocketHeartbeatReq, opts ...grpc.CallOption) (*SocketHeartbeatResp, error) {
	out := new(SocketHeartbeatResp)
	err := c.cc.Invoke(ctx, "/pb.Socket/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) Receive(ctx context.Context, in *SocketReceiveReq, opts ...grpc.CallOption) (*SocketReceiveResp, error) {
	out := new(SocketReceiveResp)
	err := c.cc.Invoke(ctx, "/pb.Socket/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocketServer is the server API for Socket service.
// All implementations must embed UnimplementedSocketServer
// for forward compatibility
type SocketServer interface {
	// Connect valid socket connect
	Connect(context.Context, *SocketConnectReq) (*SocketConnectResp, error)
	Disconnect(context.Context, *SocketDisconnectReq) (*SocketDisconnectResp, error)
	RenewOnline(context.Context, *SocketOnlineReq) (*SocketOnlineResp, error)
	Heartbeat(context.Context, *SocketHeartbeatReq) (*SocketHeartbeatResp, error)
	Receive(context.Context, *SocketReceiveReq) (*SocketReceiveResp, error)
	mustEmbedUnimplementedSocketServer()
}

// UnimplementedSocketServer must be embedded to have forward compatible implementations.
type UnimplementedSocketServer struct {
}

func (UnimplementedSocketServer) Connect(context.Context, *SocketConnectReq) (*SocketConnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSocketServer) Disconnect(context.Context, *SocketDisconnectReq) (*SocketDisconnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedSocketServer) RenewOnline(context.Context, *SocketOnlineReq) (*SocketOnlineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewOnline not implemented")
}
func (UnimplementedSocketServer) Heartbeat(context.Context, *SocketHeartbeatReq) (*SocketHeartbeatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSocketServer) Receive(context.Context, *SocketReceiveReq) (*SocketReceiveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedSocketServer) mustEmbedUnimplementedSocketServer() {}

// UnsafeSocketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocketServer will
// result in compilation errors.
type UnsafeSocketServer interface {
	mustEmbedUnimplementedSocketServer()
}

func RegisterSocketServer(s grpc.ServiceRegistrar, srv SocketServer) {
	s.RegisterService(&Socket_ServiceDesc, srv)
}

func _Socket_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Socket/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Connect(ctx, req.(*SocketConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketDisconnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Socket/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Disconnect(ctx, req.(*SocketDisconnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_RenewOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).RenewOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Socket/RenewOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).RenewOnline(ctx, req.(*SocketOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketHeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Socket/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Heartbeat(ctx, req.(*SocketHeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketReceiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Socket/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Receive(ctx, req.(*SocketReceiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Socket_ServiceDesc is the grpc.ServiceDesc for Socket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Socket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Socket",
	HandlerType: (*SocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Socket_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Socket_Disconnect_Handler,
		},
		{
			MethodName: "RenewOnline",
			Handler:    _Socket_RenewOnline_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Socket_Heartbeat_Handler,
		},
		{
			MethodName: "Receive",
			Handler:    _Socket_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
