version: '3.8'

services:
  comet:
    image: ghcr.io/sokuim/sokuim-server/core:latest
    container_name: sokuim-core
    restart: always
    ports:
      - "6071:6071"
    volumes:
      # - ./etc:/app/etc # 挂载配置文件目录(根据实际情况调整)
      - /etc/localtime:/etc/localtime:ro # 同步宿主机时区
    logging:
      driver: "json-file"
      options:
        max-size: "100m" # 单个文件最大 100M
        max-file: "3" # 最多保留3个日志文件