version: '3.8'

services:
  core:
    image: ghcr.io/sokuim/sokuim-server/core:latest
    container_name: sokuim-core
    restart: always
    ports:
      - "${CORE_PORT}:8083"
    volumes:
      - /etc/localtime:/etc/localtime:ro # 同步宿主机时区
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:8083" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
